import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@spotfinder2/ui/src/app/globals.css";
import { ApolloProvider } from "@spotfinder2/network/src/config/apollo";
import { SessionProvider } from "@spotfinder2/ui/src/components/molecules/SessionProvider";
import { Header } from "@spotfinder2/ui/src/components/organisms/Header";
import { MenuItem } from "@spotfinder2/util/types";
import { ToastContainer } from "@spotfinder2/ui/src/components/molecules/Toast";
import { Container } from "@spotfinder2/ui/src/components/atoms/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotfinder2",
  description: "Generated by create next app",
};
const MenuItems: MenuItem[] = [
  { label: "Home", href: "/" },
  { label: "Search", href: "/search" },
  { label: "Bookings", href: "/bookings" },
  { label: "About", href: "/about" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body className={inter.className + " bg-gray-25"}>
            <Header menuItems={MenuItems} />
            <Container>{children}</Container>
            <ToastContainer />
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
