import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@spotfinder2/ui/src/app/globals.css";
import { ApolloProvider } from "@spotfinder2/network/src/config/apollo";
import { SessionProvider } from "@spotfinder2/ui/src/components/molecules/SessionProvider";
import { Header } from "@spotfinder2/ui/src/components/organisms/Header";
import { MenuItem } from "@spotfinder2/util/types";
import { ToastContainer } from "@spotfinder2/ui/src/components/molecules/Toast";
import { Container } from "@spotfinder2/ui/src/components/atoms/Container";
import { IsAdmin } from "@spotfinder2/ui/src/components/organisms/IsAdmin";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotfinder2 | Admin",
  description: "Generated by create next app",
};
const MenuItems: MenuItem[] = [
  { label: "Garages", href: "/" },
  { label: "Admins", href: "/manageAdmins" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-25"}>
        <SessionProvider>
          <ApolloProvider>
            <Header menuItems={MenuItems} />
            <Container>{children}</Container>
            <ToastContainer />
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
