import type { Metadata } from "next";
import "@spotfinder2/ui/src/app/globals.css";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@spotfinder2/network/src/config/apollo";
import { SessionProvider } from "@spotfinder2/ui/src/components/molecules/SessionProvider";
import { Header } from "@spotfinder2/ui/src/components/organisms/Header";
import { MenuItem } from "@spotfinder2/util/types";
import { ToastContainer } from "@spotfinder2/ui/src/components/molecules/Toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotfinder2 | Manager",
  description: "Generated by create next app",
};
const MenuItems: MenuItem[] = [
  { label: "New Garage", href: "/createGarage" },
  { label: "Valets", href: "/valets" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-25"}>
        <SessionProvider>
          <ApolloProvider>
            <Header menuItems={MenuItems} />
            {children}
            <ToastContainer />
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
